### ISSUE TITLE
How make it work ?

### ISSUE THREAD

**Issue by kristoff2016** [fxm90/GradientLoadingBar#6]
I followed your instructions but it does not work for me 
Any config ?

thanks

**Comment by kristoff2016** [comment]
I installed your lib via pod but I don't know why it is not show anything 
any that I missed ?

**Comment by iamsanketray123** [comment]
Actually the same for me. I can't get it to work. Its just two lines of code.

**Comment by iamsanketray123** [comment]
`let gradientLoadingBar = GradientLoadingBar.shared`
`gradientLoadingBar.show()`
This works for some reason.

**Comment by fxm90** [comment]
Hello, I might have an idea where the issue is coming from. If `GradientLoadingBar.shared` is working, it sounds like you're not keeping a reference to the local instance `let gradientLoadingBar = GradientLoadingBar()` inside your view controller.

I think the docs might be a bit misleading here 🙈  Could you please try whether the loading bar is shown, if you save the instance on a property on your view controller? E.g.:

```
class SampleViewController: UIViewController {

    private let gradientLoadingBar = GradientLoadingBar()

    func updateLoadingBarVisibility(_ isVisible: Bool) {
        if isVisible {
            gradientLoadingBar.show()
        } else {
            gradientLoadingBar.hide()
        }
    }
}
```

Then I'm gonna update the documentation. Thanks 👍
